"""sync model drift to current models

Revision ID: 246fdd13f6ee
Revises: c7d8e9f0a1b2
Create Date: 2026-06-03 19:39:46.952036

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '246fdd13f6ee'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'context_audio_url',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_unique_constraint('uq_user_languages', 'user_languages', ['user_id', 'language_id'])
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               comment='User email (unique among active users, see uq_users_email_active)',
               existing_comment='User email (unique, used for login)',
               existing_nullable=False)
    op.alter_column('users', 'pending_email',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               comment='New email awaiting confirmation (email change flow)',
               existing_comment='New email awaiting confirmation',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               comment='Display name (optional, unique among active users, see uq_users_username_active)',
               existing_comment='Display name (optional, unique if provided)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               comment='Display name (optional, unique if provided)',
               existing_comment='Display name (optional, unique among active users, see uq_users_username_active)',
               existing_nullable=True)
    op.alter_column('users', 'pending_email',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               comment='New email awaiting confirmation',
               existing_comment='New email awaiting confirmation (email change flow)',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               comment='User email (unique, used for login)',
               existing_comment='User email (unique among active users, see uq_users_email_active)',
               existing_nullable=False)
    op.drop_constraint('uq_user_languages', 'user_languages', type_='unique')
    op.alter_column('items', 'context_audio_url',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
