"""sync model drift: text cols, uq_user_languages, pending_email comment

Revision ID: 3a0082bac017
Revises: b3c4d5e6f7a8
Create Date: 2026-05-30 19:16:17.205717

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a0082bac017"
down_revision: Union[str, Sequence[str], None] = "b3c4d5e6f7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items",
        "context_audio_url",
        existing_type=sa.VARCHAR(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_unique_constraint("uq_user_languages", "user_languages", ["user_id", "language_id"])
    op.alter_column(
        "users",
        "pending_email",
        existing_type=sa.VARCHAR(),
        type_=sa.TEXT(),
        comment="New email awaiting confirmation (email change flow)",
        existing_comment="New email awaiting confirmation",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "pending_email",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(),
        comment="New email awaiting confirmation",
        existing_comment="New email awaiting confirmation (email change flow)",
        existing_nullable=True,
    )
    op.drop_constraint("uq_user_languages", "user_languages", type_="unique")
    op.alter_column(
        "items",
        "context_audio_url",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
