"""small changes

Revision ID: 7d146174ed2c
Revises: 497834a509ad
Create Date: 2026-04-19 14:07:50.634195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d146174ed2c"
down_revision: Union[str, Sequence[str], None] = "497834a509ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE pending_sessions "
        "ALTER COLUMN raw_events_json TYPE JSONB "
        "USING raw_events_json::jsonb"
    )
    op.execute(
        "ALTER TABLE pending_sessions "
        "ALTER COLUMN session_state_json TYPE JSONB "
        "USING session_state_json::jsonb"
    )
    op.alter_column(
        "pending_sessions",
        "saved_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "study_reviews",
        "reviewed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_set_library",
        "added_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column(
        "user_stats_total",
        sa.Column("last_recalculated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("user_stats_total", "last_repaired")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_stats_total",
        sa.Column(
            "last_repaired",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user_stats_total", "last_recalculated_at")
    op.alter_column(
        "user_set_library",
        "added_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "study_reviews",
        "reviewed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "pending_sessions",
        "saved_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "pending_sessions",
        "session_state_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_comment="Snapshot of SessionState metadata (item_order, current_index, config)",
        existing_nullable=False,
    )
    op.alter_column(
        "pending_sessions",
        "raw_events_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        comment="JSON array of RawAnswerEvent — buffered per-answer data",
        existing_comment="Array of RawAnswerEvent dicts — buffered per-answer data",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
